// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd6rN1H3G71eTt_-nQ_6z_jaDNzSgZNmM',
    appId: '1:186488893880:web:70751138e454cf4e831f4d',
    messagingSenderId: '186488893880',
    projectId: 'home-app-36dfe',
    authDomain: 'home-app-36dfe.firebaseapp.com',
    storageBucket: 'home-app-36dfe.appspot.com',
    measurementId: 'G-2ZCS2YB5LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYqTlFx8gWdo8MQOWOEyK6FONAW9omG4',
    appId: '1:186488893880:android:ff9cca51d8f679d7831f4d',
    messagingSenderId: '186488893880',
    projectId: 'home-app-36dfe',
    storageBucket: 'home-app-36dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHoFXg_tho9O2i_fQH5wVt56h1cfSNe8',
    appId: '1:186488893880:ios:dddb3ed6ae50a5ae831f4d',
    messagingSenderId: '186488893880',
    projectId: 'home-app-36dfe',
    storageBucket: 'home-app-36dfe.appspot.com',
    iosBundleId: 'com.example.home_services_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHoFXg_tho9O2i_fQH5wVt56h1cfSNe8',
    appId: '1:186488893880:ios:dddb3ed6ae50a5ae831f4d',
    messagingSenderId: '186488893880',
    projectId: 'home-app-36dfe',
    storageBucket: 'home-app-36dfe.appspot.com',
    iosBundleId: 'com.example.home_services_app',
  );
}
